### ISSUE TITLE
Create a new branch for the Electron Application

### ISSUE THREAD

**Issue by shivangswain** [astrosonic/forge#17]
GitHub doesn't allow me to request a PR to a new branch the is not already present. You'll have to create a new branch and then only can I PR to the new branch.

**Comment by t0xic0der** [comment]
Cool. A new branch has been created called [`electron-application`](https://github.com/astrosonic/forge/tree/electron-application) diverging from [`master`](https://github.com/astrosonic/forge). I could have diverged it from the [`modern-layout`](https://github.com/astrosonic/forge/tree/modern-layout) but by far the older layout is complete and can be easily ported to. Additions to [`modern-layout`](https://github.com/astrosonic/forge/tree/modern-layout) can be added to this branch with patches.
