### ISSUE TITLE
Unequal card header thicknesses in Contacts page

### ISSUE THREAD

**Issue by t0xic0der** [astrosonic/forge#20]
OCD guy right here but even you'd feel unsettled when two identical looking card layouts are displayed one after the other but one of their header is thicker than another.

**Reason**
- The presence of the search bar makes the bar go slightly thicker
- Thickness is an issue because it makes the text of card header look top-aligned

The files can be found in the `modern-layout` branch of this repository. Specifically look for `contocts.html` file inside the `templates` folder which has the issue.

![Screenshot from 2020-06-18 00-00-56](https://user-images.githubusercontent.com/49605954/84936625-2a85a100-b0f8-11ea-9827-f335abfd862f.png)

**Comment by Ank221199** [comment]
I will pick up this

**Comment by ArindamPal-0** [comment]
I would like to fix this...

**Comment by t0xic0der** [comment]
Cool, @Ank221199 and @ArindamPal-0 you both can fork the project and start adding your respective changes in a new branch. When the changes are complete, make a PR and assign either me for review. If the changes made are satisfactory we will merge it to master or revert back to you with more suggested changes.

Good luck. This issue has been assigned to both of you.

P.S. Please avoid merging without consent and in case of any conflict during the merge, please let know before rebasing.

**Comment by t0xic0der** [comment]
Fixed in the latest commit [5c719d6](https://github.com/astrosonic/forge/commit/5c719d68fd92168e45154e7d8c7664d3bda53d62).
